<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Sims4ModSieve.Packages</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LlamaLogic.Packages" Version="3.8.2" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sims4ModSieve.Core\Sims4ModSieve.Core.csproj" />
  </ItemGroup>

</Project>
